/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author Dilan Lara
 */
public class PantallaDocente extends javax.swing.JFrame {

    /**
     * Creates new form PantallaDocente
     */
    public PantallaDocente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        InicioDocente = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        VerProyectos = new javax.swing.JMenuItem();
        MenuCrearTema = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        VerEstudiantes = new javax.swing.JMenuItem();
        CerrarMenuD = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        Asignar = new javax.swing.JMenuItem();
        VerGrupos = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        AsignarProyecto = new javax.swing.JMenuItem();
        AsignacionProyecto = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        Resultados = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setLocation(new java.awt.Point(0, 0));

        InicioDocente.setBackground(new java.awt.Color(255, 255, 255));
        InicioDocente.setPreferredSize(new java.awt.Dimension(1080, 720));

        javax.swing.GroupLayout InicioDocenteLayout = new javax.swing.GroupLayout(InicioDocente);
        InicioDocente.setLayout(InicioDocenteLayout);
        InicioDocenteLayout.setHorizontalGroup(
            InicioDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1080, Short.MAX_VALUE)
        );
        InicioDocenteLayout.setVerticalGroup(
            InicioDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 866, Short.MAX_VALUE)
        );

        jMenuBar1.setBackground(new java.awt.Color(204, 204, 255));
        jMenuBar1.setForeground(new java.awt.Color(51, 0, 51));

        jMenu1.setText("Menu Principal");

        VerProyectos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        VerProyectos.setText("Proyectos");
        VerProyectos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerProyectosActionPerformed(evt);
            }
        });
        jMenu1.add(VerProyectos);

        MenuCrearTema.setText("Crear Proyectos De Investigacion");
        MenuCrearTema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCrearTemaActionPerformed(evt);
            }
        });
        jMenu1.add(MenuCrearTema);
        jMenu1.add(jSeparator1);

        VerEstudiantes.setText("Ver Estudiantes");
        VerEstudiantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerEstudiantesActionPerformed(evt);
            }
        });
        jMenu1.add(VerEstudiantes);

        CerrarMenuD.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.ALT_DOWN_MASK));
        CerrarMenuD.setText("Cerrar Sesion");
        CerrarMenuD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CerrarMenuDActionPerformed(evt);
            }
        });
        jMenu1.add(CerrarMenuD);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Asignar Grupos");

        Asignar.setText("Asignar");
        Asignar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AsignarActionPerformed(evt);
            }
        });
        jMenu3.add(Asignar);

        VerGrupos.setText("Ver Grupos ");
        VerGrupos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerGruposActionPerformed(evt);
            }
        });
        jMenu3.add(VerGrupos);

        jMenuBar1.add(jMenu3);

        jMenu2.setText("Estado Proyecto");

        AsignarProyecto.setText("Ver Asignaciones Proyecto");
        AsignarProyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AsignarProyectoActionPerformed(evt);
            }
        });
        jMenu2.add(AsignarProyecto);

        AsignacionProyecto.setText("Crear Asignacion de Proyecto");
        AsignacionProyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AsignacionProyectoActionPerformed(evt);
            }
        });
        jMenu2.add(AsignacionProyecto);
        jMenu2.add(jSeparator2);

        Resultados.setText("Dar Resultados");
        Resultados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResultadosActionPerformed(evt);
            }
        });
        jMenu2.add(Resultados);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(InicioDocente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(InicioDocente, javax.swing.GroupLayout.PREFERRED_SIZE, 866, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VerProyectosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerProyectosActionPerformed
        // TODO add your handling code here:
        VerProyecto ventana=new VerProyecto();
        InicioDocente.add(ventana);
        ventana.show();
    }//GEN-LAST:event_VerProyectosActionPerformed

    private void MenuCrearTemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCrearTemaActionPerformed
        // TODO add your handling code here:
        CrearProyecto ventana=new CrearProyecto();
        InicioDocente.add(ventana);
        ventana.show();
       
        
    }//GEN-LAST:event_MenuCrearTemaActionPerformed

    private void CerrarMenuDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CerrarMenuDActionPerformed
        // TODO add your handling code here:
        
        InicioDeSesion inicio =new InicioDeSesion();
        inicio.setVisible(true);
    // Cerrar la ventana actual
         this.dispose();
    }//GEN-LAST:event_CerrarMenuDActionPerformed

    private void VerEstudiantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerEstudiantesActionPerformed
        // TODO add your handling code here:
        VerEstudiantes ventana= new VerEstudiantes();
        InicioDocente.add(ventana);
        ventana.show();
    }//GEN-LAST:event_VerEstudiantesActionPerformed

    private void AsignarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AsignarActionPerformed
        // TODO add your handling code here:
        CrearGrupo grupo =new CrearGrupo();
        InicioDocente.add(grupo);
        grupo.show();
    }//GEN-LAST:event_AsignarActionPerformed

    private void VerGruposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerGruposActionPerformed
        // TODO add your handling code here:
        VerGrupos gr =new VerGrupos();
        InicioDocente.add(gr);
        gr.show();
    }//GEN-LAST:event_VerGruposActionPerformed

    private void AsignarProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AsignarProyectoActionPerformed
        // TODO add your handling code here:
        VerAsignacion as =new VerAsignacion();
        InicioDocente.add(as);
        as.show();
    }//GEN-LAST:event_AsignarProyectoActionPerformed

    private void AsignacionProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AsignacionProyectoActionPerformed
        // TODO add your handling code here:
        CrearAsignacion ca=new CrearAsignacion();
        InicioDocente.add(ca);
        ca.show();
    }//GEN-LAST:event_AsignacionProyectoActionPerformed

    private void ResultadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResultadosActionPerformed
        // TODO add your handling code here:
        AsignarResultados re=new AsignarResultados();
        InicioDocente.add(re);
        re.show();
        
    }//GEN-LAST:event_ResultadosActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AsignacionProyecto;
    private javax.swing.JMenuItem Asignar;
    private javax.swing.JMenuItem AsignarProyecto;
    private javax.swing.JMenuItem CerrarMenuD;
    private javax.swing.JPanel InicioDocente;
    private javax.swing.JMenuItem MenuCrearTema;
    private javax.swing.JMenuItem Resultados;
    private javax.swing.JMenuItem VerEstudiantes;
    private javax.swing.JMenuItem VerGrupos;
    private javax.swing.JMenuItem VerProyectos;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
