/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author Dilan Lara
 */
public class PantallaDocente extends javax.swing.JFrame {

    /**
     * Creates new form PantallaDocente
     */
    public PantallaDocente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        InicioDocente = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        VerProyectos = new javax.swing.JMenuItem();
        MenuCrearTema = new javax.swing.JMenuItem();
        VerEstudiantes = new javax.swing.JMenuItem();
        CerrarMenuD = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        Asignar = new javax.swing.JMenuItem();
        VerGrupos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout InicioDocenteLayout = new javax.swing.GroupLayout(InicioDocente);
        InicioDocente.setLayout(InicioDocenteLayout);
        InicioDocenteLayout.setHorizontalGroup(
            InicioDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1087, Short.MAX_VALUE)
        );
        InicioDocenteLayout.setVerticalGroup(
            InicioDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 652, Short.MAX_VALUE)
        );

        jMenu1.setText("Menu Proyectos");

        VerProyectos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        VerProyectos.setText("Proyectos");
        VerProyectos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerProyectosActionPerformed(evt);
            }
        });
        jMenu1.add(VerProyectos);

        MenuCrearTema.setText("Crear Proyectos De Investigacion");
        MenuCrearTema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCrearTemaActionPerformed(evt);
            }
        });
        jMenu1.add(MenuCrearTema);

        VerEstudiantes.setText("Ver Estudiantes");
        VerEstudiantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerEstudiantesActionPerformed(evt);
            }
        });
        jMenu1.add(VerEstudiantes);

        CerrarMenuD.setText("Cerrar Sesion");
        CerrarMenuD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CerrarMenuDActionPerformed(evt);
            }
        });
        jMenu1.add(CerrarMenuD);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Asignar Proyectos");

        Asignar.setText("Asignar");
        Asignar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AsignarActionPerformed(evt);
            }
        });
        jMenu3.add(Asignar);

        VerGrupos.setText("Ver Grupos ");
        VerGrupos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerGruposActionPerformed(evt);
            }
        });
        jMenu3.add(VerGrupos);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(InicioDocente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(InicioDocente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VerProyectosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerProyectosActionPerformed
        // TODO add your handling code here:
        VerProyecto ventana=new VerProyecto();
        InicioDocente.add(ventana);
        ventana.show();
    }//GEN-LAST:event_VerProyectosActionPerformed

    private void MenuCrearTemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCrearTemaActionPerformed
        // TODO add your handling code here:
        CrearProyecto ventana=new CrearProyecto();
        InicioDocente.add(ventana);
        ventana.show();
       
        
    }//GEN-LAST:event_MenuCrearTemaActionPerformed

    private void CerrarMenuDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CerrarMenuDActionPerformed
        // TODO add your handling code here:
        
        InicioDeSesion inicio =new InicioDeSesion();
        inicio.setVisible(true);
    // Cerrar la ventana actual
         this.dispose();
    }//GEN-LAST:event_CerrarMenuDActionPerformed

    private void VerEstudiantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerEstudiantesActionPerformed
        // TODO add your handling code here:
        VerEstudiantes ventana= new VerEstudiantes();
        InicioDocente.add(ventana);
        ventana.show();
    }//GEN-LAST:event_VerEstudiantesActionPerformed

    private void AsignarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AsignarActionPerformed
        // TODO add your handling code here:
        CrearGrupo grupo =new CrearGrupo();
        InicioDocente.add(grupo);
        grupo.show();
    }//GEN-LAST:event_AsignarActionPerformed

    private void VerGruposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerGruposActionPerformed
        // TODO add your handling code here:
        VerGrupos gr =new VerGrupos();
        InicioDocente.add(gr);
        gr.show();
    }//GEN-LAST:event_VerGruposActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Asignar;
    private javax.swing.JMenuItem CerrarMenuD;
    private javax.swing.JPanel InicioDocente;
    private javax.swing.JMenuItem MenuCrearTema;
    private javax.swing.JMenuItem VerEstudiantes;
    private javax.swing.JMenuItem VerGrupos;
    private javax.swing.JMenuItem VerProyectos;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
